### ISSUE TITLE
Load new images to demo, run data update utility and test.

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#14] opened 2018-08-18 02:15 UTC
Once the data model changes (to support the proxy submitter use case) have been implemented in all components of the system. New images (`fcrepo`, `ember` etc.) will need to be deployed to demo, and the update utility run against the database.

**Comment by karenhanson** [comment] 2018-11-13 17:52
@htpvu I think this is a duplicate of #70 and can be closed.

**Closed** 2018-11-13 19:34 UTC
Labels: data-modeling, proxy-submitter
